In [ ]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
peng = pd.read_csv('Datasets//penguins.csv')

In [ ]:
peng 

In [ ]:
peng.describe()

In [ ]:
peng.isnull().sum()

In [ ]:
peng['bill_length_mm'] = peng['bill_length_mm'].fillna(peng['bill_length_mm'].mean())

In [ ]:
peng['bill_depth_mm'] = peng['bill_depth_mm'].fillna(peng['bill_depth_mm'].mean())

In [ ]:
peng['flipper_length_mm'] = peng['flipper_length_mm'].fillna(peng['flipper_length_mm'].mean())

In [ ]:
peng['body_mass_g'] = peng['body_mass_g'].fillna(peng['body_mass_g'].mean())

In [ ]:
peng['sex'] = peng['sex'].fillna(peng['sex'].mode()[0])

In [45]:
peng.isnull().sum()

rowid                0
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
wkilo                0
dtype: int64

In [46]:
peng['year'] =peng['year'].astype('category')

In [47]:
peng['island'] =peng['island'].astype('category')

In [48]:
peng['species'] =peng['species'].astype('category')

In [49]:
peng['sex'] =peng['sex'].astype('category')

In [50]:
peng['rowid'] =peng['rowid'].astype('category')

In [51]:
peng.dtypes

rowid                category
species              category
island               category
bill_length_mm        float64
bill_depth_mm         float64
flipper_length_mm     float64
body_mass_g           float64
sex                  category
year                 category
wkilo                 float64
dtype: object

In [52]:
peng['species'].value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [53]:
peng[peng['species'] == 'Adelie']

rowid species     island  bill_length_mm  bill_depth_mm  \
0       1  Adelie  Torgersen        39.10000       18.70000   
1       2  Adelie  Torgersen        39.50000       17.40000   
2       3  Adelie  Torgersen        40.30000       18.00000   
3       4  Adelie  Torgersen        43.92193       17.15117   
4       5  Adelie  Torgersen        36.70000       19.30000   
..    ...     ...        ...             ...            ...   
147   148  Adelie      Dream        36.60000       18.40000   
148   149  Adelie      Dream        36.00000       17.80000   
149   150  Adelie      Dream        37.80000       18.10000   
150   151  Adelie      Dream        36.00000       17.10000   
151   152  Adelie      Dream        41.50000       18.50000   

     flipper_length_mm  body_mass_g     sex  year  wkilo  
0           181.000000  3750.000000    male  2007    3.8  
1           186.000000  3800.000000  female  2007    3.8  
2           195.000000  3250.000000  female  2007    3.2  
3           200.915205  4201.754386    male  2007    4.2  
4           193.000000  3450.000000  female  2007    3.4  
..                 ...          ...     ...   ...    ...  
147         184.000000  3475.000000  female  2009    3.5  
148         195.000000  3450.000000  female  2009    3.4  
149         193.000000  3750.000000    male  2009    3.8  
150         187.000000  3700.000000  female  2009    3.7  
151         201.000000  4000.000000    male  2009    4.0  

[152 rows x 10 columns]

<h2> #1 Does the penguins specie Adelie lives exclusively on an island? 
<h1> Insight No. 1 Penguins does not live exclusively on an Island

<h2> Adelie on Biscoe Island

In [54]:
peng['species'] == 'Adelie'

0       True
1       True
2       True
3       True
4       True
       ...  
339    False
340    False
341    False
342    False
343    False
Name: species, Length: 344, dtype: bool

In [55]:
adelie_biscoe = peng[(peng['species'] == 'Adelie') & (peng['island'] == 'Biscoe')] 

In [56]:
peng[(peng['species'] == 'Adelie') & (peng['island'] == 'Biscoe')].count()

rowid                44
species              44
island               44
bill_length_mm       44
bill_depth_mm        44
flipper_length_mm    44
body_mass_g          44
sex                  44
year                 44
wkilo                44
dtype: int64

In [57]:
peng['island'].value_counts()

island
Biscoe       168
Dream        124
Torgersen     52
Name: count, dtype: int64

<h2> Adelie on Biscoe Dream

In [58]:
adelie_dream = peng[(peng['species'] == 'Adelie') & (peng['island'] == 'Dream')]

In [59]:
peng[(peng['species'] == 'Adelie') & (peng['island'] == 'Dream')].count()

rowid                56
species              56
island               56
bill_length_mm       56
bill_depth_mm        56
flipper_length_mm    56
body_mass_g          56
sex                  56
year                 56
wkilo                56
dtype: int64

<h2> Adelie on Biscoe Torgersen

In [60]:
adelie_torg = peng[(peng['species'] == 'Adelie') & (peng['island'] == 'Torgersen')]

In [61]:
peng[(peng['species'] == 'Adelie') & (peng['island'] == 'Torgersen')].count()

rowid                52
species              52
island               52
bill_length_mm       52
bill_depth_mm        52
flipper_length_mm    52
body_mass_g          52
sex                  52
year                 52
wkilo                52
dtype: int64

In [62]:
peng['species'].value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

<h2> Gentoo on Biscoe Island

<h1> Insight No. 2 Gentoo only live in Gentoo Island

In [63]:
gentoo_bis = peng[(peng['species'] == 'Gentoo') & (peng['island'] == 'Biscoe')].count()

In [64]:
peng[(peng['species'] == 'Gentoo') & (peng['island'] == 'Biscoe')].count()

rowid                124
species              124
island               124
bill_length_mm       124
bill_depth_mm        124
flipper_length_mm    124
body_mass_g          124
sex                  124
year                 124
wkilo                124
dtype: int64

<h2> Gentoo on Dream Island

In [65]:
gentoo_drm = peng[(peng['species'] == 'Gentoo') & (peng['island'] == 'Dream')].count()

In [66]:
peng[(peng['species'] == 'Gentoo') & (peng['island'] == 'Dream')].count()

rowid                0
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
wkilo                0
dtype: int64

<h2> Gentoo on Torgersen Island

In [67]:
gentoo_torg = peng[(peng['species'] == 'Gentoo') & (peng['island'] == 'Torgersen')].count()

In [68]:
peng[(peng['species'] == 'Gentoo') & (peng['island'] == 'Torgersen')].count()

rowid                0
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
wkilo                0
dtype: int64

<h2> Chinstrap on Biscoe Island

In [69]:
chins_bisc = peng[(peng['species'] == 'Chinstrap') & (peng['island'] == 'Biscoe')].count()

In [70]:
peng[(peng['species'] == 'Chinstrap') & (peng['island'] == 'Biscoe')].count()

rowid                0
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
wkilo                0
dtype: int64

<h2> Chinstrap on Dream Island

In [71]:
chins_drm = peng[(peng['species'] == 'Chinstrap') & (peng['island'] == 'Dream')].count()

In [72]:
peng[(peng['species'] == 'Chinstrap') & (peng['island'] == 'Dream')].count()

rowid                68
species              68
island               68
bill_length_mm       68
bill_depth_mm        68
flipper_length_mm    68
body_mass_g          68
sex                  68
year                 68
wkilo                68
dtype: int64

<h2> Chinstrap on Torgersen Island

In [73]:
chins_torg = peng[(peng['species'] == 'Chinstrap') & (peng['island'] == 'Dream')].count()

In [74]:
peng[(peng['species'] == 'Chinstrap') & (peng['island'] == 'Torgersen')].count()

rowid                0
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
wkilo                0
dtype: int64

In [75]:
peng['island'].value_counts()

island
Biscoe       168
Dream        124
Torgersen     52
Name: count, dtype: int64

<h1> Insight No. 3 Majority of penguins live in Biscoe Island

<h1> Does the Island affects the weight or body mass of a penguin specie?

In [76]:
peng['wkilo'] = np.round(peng['body_mass_g']/1000, 1)

In [77]:
peng

rowid    species     island  bill_length_mm  bill_depth_mm  \
0       1     Adelie  Torgersen        39.10000       18.70000   
1       2     Adelie  Torgersen        39.50000       17.40000   
2       3     Adelie  Torgersen        40.30000       18.00000   
3       4     Adelie  Torgersen        43.92193       17.15117   
4       5     Adelie  Torgersen        36.70000       19.30000   
..    ...        ...        ...             ...            ...   
339   340  Chinstrap      Dream        55.80000       19.80000   
340   341  Chinstrap      Dream        43.50000       18.10000   
341   342  Chinstrap      Dream        49.60000       18.20000   
342   343  Chinstrap      Dream        50.80000       19.00000   
343   344  Chinstrap      Dream        50.20000       18.70000   

     flipper_length_mm  body_mass_g     sex  year  wkilo  
0           181.000000  3750.000000    male  2007    3.8  
1           186.000000  3800.000000  female  2007    3.8  
2           195.000000  3250.000000  female  2007    3.2  
3           200.915205  4201.754386    male  2007    4.2  
4           193.000000  3450.000000  female  2007    3.4  
..                 ...          ...     ...   ...    ...  
339         207.000000  4000.000000    male  2009    4.0  
340         202.000000  3400.000000  female  2009    3.4  
341         193.000000  3775.000000    male  2009    3.8  
342         210.000000  4100.000000    male  2009    4.1  
343         198.000000  3775.000000  female  2009    3.8  

[344 rows x 10 columns]

<h1> Adelie Biscoe

In [78]:
adelie_biscoe['wkilo'].mean()

np.float64(3.715909090909091)

In [79]:
np.round(adelie_biscoe['wkilo'].mean(), 1)

np.float64(3.7)

<h1> Adelie Dream

In [80]:
adelie_dream['wkilo'].mean()

np.float64(3.6910714285714286)

In [81]:
np.round(adelie_dream['wkilo'].mean(), 1)

np.float64(3.7)

<h1> Adelie Torgersen

In [82]:
adelie_torg['wkilo'].mean()

np.float64(3.7115384615384617)

In [83]:
np.round(adelie_torg['wkilo'].mean(), 1)

np.float64(3.7)

<h1> Gentoo Biscoe

In [84]:
gentoo_bis['wkilo'].mean()

np.float64(124.0)

In [85]:
np.round(gentoo_bis['wkilo'].mean(), 1)

np.float64(124.0)

<h1> Gentoo Dream

In [86]:
gentoo_drm['wkilo'].mean()

np.float64(0.0)

In [87]:
np.round(gentoo_drm['wkilo'].mean(), 1)

np.float64(0.0)

<h1> Gentoo Torgersen

In [88]:
gentoo_torg['wkilo'].mean()

np.float64(0.0)

In [89]:
np.round(gentoo_torg['wkilo'].mean(), 1)

np.float64(0.0)

<h1> Chinstrap Biscoe

In [90]:
chins_bisc['wkilo'].mean()

np.float64(0.0)

In [91]:
np.round(chins_bisc['wkilo'].mean(), 1)

np.float64(0.0)

<h1> Chinstrap Dream

In [92]:
chins_drm['wkilo'].mean()

np.float64(68.0)

In [93]:
np.round(chins_drm['wkilo'].mean(), 1)

np.float64(68.0)

<h1> Chinstrap Torgersen

In [94]:
chins_torg['wkilo'].mean()

np.float64(68.0)

In [95]:
np.round(chins_torg['wkilo'].mean(), 1)

np.float64(68.0)

<h1> Insight No. 4 The Average Kilo Adelie regardless of island is 3.7 

<h1> Insight No. 5 The Average Kilo of Gentoo on Biscoe Island is 124.0

<h1> Insight No. 6 The Average Kilo of Chinstrap on Torgersen and Dream Islan is 68.0

<h1> Insight No. 7  Gentoo has the highest average Kilo.

In [96]:
peng_agg = peng.groupby(["species", "island", "sex"]).count()

C:\Users\LAB4-StudentPC37\AppData\Local\Temp\ipykernel_5812\4097172016.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  peng_agg = peng.groupby(["species", "island", "sex"]).count()


In [97]:
peng_agg

rowid  bill_length_mm  bill_depth_mm  \
species   island    sex                                            
Adelie    Biscoe    female     22              22             22   
                    male       22              22             22   
          Dream     female     27              27             27   
                    male       29              29             29   
          Torgersen female     24              24             24   
                    male       28              28             28   
Chinstrap Biscoe    female      0               0              0   
                    male        0               0              0   
          Dream     female     34              34             34   
                    male       34              34             34   
          Torgersen female      0               0              0   
                    male        0               0              0   
Gentoo    Biscoe    female     58              58             58   
                    male       66              66             66   
          Dream     female      0               0              0   
                    male        0               0              0   
          Torgersen female      0               0              0   
                    male        0               0              0   

                            flipper_length_mm  body_mass_g  year  wkilo  
species   island    sex                                                  
Adelie    Biscoe    female                 22           22    22     22  
                    male                   22           22    22     22  
          Dream     female                 27           27    27     27  
                    male                   29           29    29     29  
          Torgersen female                 24           24    24     24  
                    male                   28           28    28     28  
Chinstrap Biscoe    female                  0            0     0      0  
                    male                    0            0     0      0  
          Dream     female                 34           34    34     34  
                    male                   34           34    34     34  
          Torgersen female                  0            0     0      0  
                    male                    0            0     0      0  
Gentoo    Biscoe    female                 58           58    58     58  
                    male                   66           66    66     66  
          Dream     female                  0            0     0      0  
                    male                    0            0     0      0  
          Torgersen female                  0            0     0      0  
                    male                    0            0     0      0

In [98]:
peng_agg = peng.groupby(["species", "year", "sex"]).size()

C:\Users\LAB4-StudentPC37\AppData\Local\Temp\ipykernel_5812\2469604902.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  peng_agg = peng.groupby(["species", "year", "sex"]).size()


In [99]:
peng_agg

species    year  sex   
Adelie     2007  female    22
                 male      28
           2008  female    25
                 male      25
           2009  female    26
                 male      26
Chinstrap  2007  female    13
                 male      13
           2008  female     9
                 male       9
           2009  female    12
                 male      12
Gentoo     2007  female    16
                 male      18
           2008  female    22
                 male      24
           2009  female    20
                 male      24
dtype: int64

<h1> Insight No. 8  2007 has the most recorded data of male adelie.

In [100]:
peng_agg.unstack()

sex             female  male
species   year              
Adelie    2007      22    28
          2008      25    25
          2009      26    26
Chinstrap 2007      13    13
          2008       9     9
          2009      12    12
Gentoo    2007      16    18
          2008      22    24
          2009      20    24

<h2> How to use .Groupby Function

<h2> Which is heavier between penguins species in terms of SEX?

In [101]:
weight_sex = np.round(peng.groupby(['species', 'sex' ])['wkilo'].mean() , 1)

C:\Users\LAB4-StudentPC37\AppData\Local\Temp\ipykernel_5812\1633964691.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  weight_sex = np.round(peng.groupby(['species', 'sex' ])['wkilo'].mean() , 1)


In [102]:
weight_sex

species    sex   
Adelie     female    3.4
           male      4.0
Chinstrap  female    3.5
           male      3.9
Gentoo     female    4.7
           male      5.4
Name: wkilo, dtype: float64

<h1> Insight No.9 The male penguins are heavier than females. 

In [103]:
weight_yearsx = np.round(peng.groupby(['species', 'sex', 'year' ])['wkilo'].mean() , 1)

C:\Users\LAB4-StudentPC37\AppData\Local\Temp\ipykernel_5812\346156586.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  weight_yearsx = np.round(peng.groupby(['species', 'sex', 'year' ])['wkilo'].mean() , 1)


In [104]:
weight_yearsx

species    sex     year
Adelie     female  2007    3.4
                   2008    3.4
                   2009    3.3
           male    2007    4.0
                   2008    4.1
                   2009    4.0
Chinstrap  female  2007    3.6
                   2008    3.5
                   2009    3.5
           male    2007    3.8
                   2008    4.1
                   2009    3.9
Gentoo     female  2007    4.6
                   2008    4.6
                   2009    4.8
           male    2007    5.5
                   2008    5.4
                   2009    5.4
Name: wkilo, dtype: float64

In [105]:
weight_yearsx.unstack()

year              2007  2008  2009
species   sex                     
Adelie    female   3.4   3.4   3.3
          male     4.0   4.1   4.0
Chinstrap female   3.6   3.5   3.5
          male     3.8   4.1   3.9
Gentoo    female   4.6   4.6   4.8
          male     5.5   5.4   5.4

<h2> Question 10 

<h2> What year has the highest recorded weight for male and female?

<h1> Insight No. 10 2009 has the highest recorded weight for female while 2007 has the highest weight recorded for male.

<h2> Correlation Vs. Causation

<h3> Correlation between Bill Length and Bill Depth

<h2> P VALUE in Statistics

<h4> A p-value is a statistical treatment used to validate a hypothesis against observed data. It measures the probability of obtaining the observed results assuming that the null hypothesis is true. A lower p-value indicates greater statitical significance of the observed difference.

<h2> Anything above .5 means the two values has a strong correlation

<h2> Anything less than .5 meaning less or no correlation

<h1> Requirements for Correlation </h1>
<ul>
    <li> Naming the variable</li>
    <li> First columns to test</li>
    <li> .corr Function</li>
    <li> second column to test</li>
</ul>

<h1> Statistical Treatment

<h2> Pandas Default - Pearson R Correlation

<h3> Used for measuring correlation between quantitative Data.

<h2> Correlation between length of flippers and depth of filppers

In [106]:
b_leng_dep = peng ['bill_length_mm'].corr(peng['bill_depth_mm'])

In [107]:
b_leng_dep

np.float64(-0.23505287035553282)

<h2> Insight No. 11 There is no correlation between bill length and bill depth.

In [125]:
b_leng_bod = peng ['bill_length_mm'].corr(peng['body_mass_g'])

In [109]:
b_leng_bod

np.float64(0.5951098244376304)

<h1> Insight No. 12 There is strong correlation between the bill length and the body mass.

In [110]:
b_ldep_bod = peng ['bill_depth_mm'].corr(peng['body_mass_g'])

In [111]:
b_ldep_bod

np.float64(-0.4719156211860664)

<h1> Insight No. 13 There is no correlation between the bill depth and the body mass

In [123]:
b_flip = peng ['bill_depth_mm'].corr(peng['flipper_length_mm'])

In [124]:
b_flip

np.float64(-0.5838512164654122)

<h1> Insight No. 14 There is no correlation between the flipper and the bill depth.

In [112]:
peng

rowid    species     island  bill_length_mm  bill_depth_mm  \
0       1     Adelie  Torgersen        39.10000       18.70000   
1       2     Adelie  Torgersen        39.50000       17.40000   
2       3     Adelie  Torgersen        40.30000       18.00000   
3       4     Adelie  Torgersen        43.92193       17.15117   
4       5     Adelie  Torgersen        36.70000       19.30000   
..    ...        ...        ...             ...            ...   
339   340  Chinstrap      Dream        55.80000       19.80000   
340   341  Chinstrap      Dream        43.50000       18.10000   
341   342  Chinstrap      Dream        49.60000       18.20000   
342   343  Chinstrap      Dream        50.80000       19.00000   
343   344  Chinstrap      Dream        50.20000       18.70000   

     flipper_length_mm  body_mass_g     sex  year  wkilo  
0           181.000000  3750.000000    male  2007    3.8  
1           186.000000  3800.000000  female  2007    3.8  
2           195.000000  3250.000000  female  2007    3.2  
3           200.915205  4201.754386    male  2007    4.2  
4           193.000000  3450.000000  female  2007    3.4  
..                 ...          ...     ...   ...    ...  
339         207.000000  4000.000000    male  2009    4.0  
340         202.000000  3400.000000  female  2009    3.4  
341         193.000000  3775.000000    male  2009    3.8  
342         210.000000  4100.000000    male  2009    4.1  
343         198.000000  3775.000000  female  2009    3.8  

[344 rows x 10 columns]

<h2> Correlational Analysis Between Qualitative Data and Quantitative Data

<h2> Use of One way Anova

<h1> Science Python Librarry -- Known as Scipy

In [113]:
pip install scipy

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/41.0 MB ? eta -:--:--
   --- ------------------------------------ 3.7/41.0 MB 19.6 MB/s eta 0:00:02
   ------ --------------------------------- 6.6/41.0 MB 16.1 MB/s eta 0:00:03
   ------- -------------------------------- 7.6/41.0 MB 12.1 MB/s eta 0:00:03
   ------- -------------------------------- 8.1/41.0 MB 10.0 MB/s eta 0:00:04
   -------- ------------------------------- 8.9/41.0 MB 8.5 MB/s eta 0:00:04
   --------- ------------------------------ 10.2/41.0 MB 8.2 MB/s eta 0:00:04
   ------------ --------------------------- 12.3/41.0 MB 8.4 MB/s eta 0:00:04
   ------------- -------------------------- 13.9/41.0 MB 8.5 MB/s eta 0:00:04
   --------------- ------------------------ 15.5/41.0 MB 8.3 MB/s eta 0:00:04
   ----------------- ---------------------- 17.6/41.0 MB 8.5 MB/s eta 0:00:03
   ------------------- -------------------- 20.4/41.0 MB 9.0 MB/s eta 0:0


[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\LAB4-StudentPC37\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [114]:
from scipy.stats import f_oneway

In [116]:
peng[peng['sex'] == 'male']['body_mass_g']

0      3750.000000
3      4201.754386
5      3650.000000
7      4675.000000
8      3475.000000
          ...     
334    3800.000000
336    3950.000000
339    4000.000000
341    3775.000000
342    4100.000000
Name: body_mass_g, Length: 179, dtype: float64

In [121]:
f_stats, p_value = f_oneway (peng[peng['sex'] == 'male']['body_mass_g'], 
                             peng[peng['sex'] == 'female']['body_mass_g'])

In [122]:
p_value

np.float64(3.0226600487050246e-15)

<h1> Insight No. 15 There is strong correlation between the sex and the body mass.

In [119]:
f_stats, p_value = f_oneway (peng[peng['species'] == 'Adelie']['bill_length_mm'], 
                             peng[peng['species'] == 'Chinstrap']['bill_length_mm'],
                             peng[peng['species'] == 'Gentoo']['bill_length_mm'])

In [120]:
p_value

np.float64(7.233266188149441e-91)

<h1> Insight No. 16 There is strong correlation between the specie and the bill length.

In [ ]:
Does the accidents mostly happen to Rural or Urban areas?
In what weather condition accidents mostly happen?
What vehicle type has the highest number of casualties?
What road type has the highest number of casualties?
What weather condition has the highest number of casualties?
What weather condition has the highest number of casualties?
What road surface has the highest number of casualties?
Which district area has the highest number of casualties?
Which year has the highest number serious accidents?
Which light condition has the highest number of slight accidents?

Correlation
Number of casualties and surface condition.
Accident Severity and life condition.
Accident Severity and Vehicle type.
Accident Severity and District Area.
Light condition and Accident Severity


